---
title: "Hybrid_comparison"
author: "Elias Mayer"
date: "21 8 2021"
output:
  word_document: default
  html_document: default
---

Dataset: Mcomp - M3 


Evaluation in terms of mean absolute percentage error:


1. Cross-validation - ARIMA, Exponential smoothing, Multiple Aggregation Prediction Algorithm.


2. MAPPA vs. hybrid approach consisting of hybrid (auto.arima), e (ets) and z (snaive) model.



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```


```{r dynamic}

library(Mcomp)
library(forecast)
library(dplyr)
library(tsibble)
library(ggplot2)
library(ggthemes)
library(stringr)
library(MAPA)
library(forecastHybrid)



#define storage array

arr_ids <- array(NA,c(70,1))

count = 1 


#Prepare data set to include only defined data sets 

for (ex in 1:length(M3)){    
    

   if ((M3[[ex]]$period == "QUARTERLY") & (ex >= 701) & (ex <= 1400) & (ex %% 10 == 2)) {
     
    arr_ids[count,1] <- ex
       
    count = count + 1
    
   }
  
}



```



```{r dynamic1}


arr_all <- array(NA,c(70,7))

#DATA single models 

count =1 

colnames(arr_all) <- c("CV_Arima_MSE", "CV_ETS_MSE", "CV_Mappa_MSE", "choosen_model","MAPE_model" ,"type", "name_ts")

for (nameId in arr_ids) {
  
  #MAIN
  h = 8
  
  y_training <- M3[[nameId]]$x  
  y_test <- M3[[nameId]]$xx
  
  #BODY
  
  # cut sub part of training data 
  
  lenT <- (length(y_training)-2*h)
  

   far1 <- function(x, h){forecast::forecast(forecast::auto.arima(x), h = h)}
   
   e_arima <- forecast::tsCV(y_training, far1, initial = lenT)
   
   mse <- sqrt(mean(e_arima^2, na.rm=TRUE))
   
   
   far2 <- function(x, h){forecast::forecast(forecast::ets(x), h = h)}
   
   e_ets <- forecast::tsCV(y_training, far2, initial = lenT)
   
   mse_2 <- sqrt(mean(e_ets^2, na.rm=TRUE))
   
   #------------------------------------------
   
   
   arr_all[count,1] <- mse
   arr_all[count,2] <- mse_2
   
   
   #------------------------------------------ MAPA function
   
   
   fmapa <- function(y, h = 8) {
   result <- MAPA::mapa(y, fh = h, conf.lvl = c(0.8, 0.95))
   list(mean = result$outfor)
   }
   
   #-----------------------------------------
   
   e_MAPA <- forecast::tsCV(y_training, fmapa, initial = lenT)
   
   mse_3 <- sqrt(mean(e_MAPA^2, na.rm=TRUE))
   
   arr_all[count,3] <- mse_3
   
   #---------------------actual fit
   
   chosenM <- ""
   
   
   #Compare and use the appropriate model 
   
   if(mse < mse_2 & mse < mse_3){
     
    fitX <- auto.arima(y_training)
    fc_ <- forecast::forecast(fitX, h=8)$mean 
    chosenM <- "arima"
    accO <- forecast::accuracy(fc_,y_test)
    
   }
   else if(mse_2 < mse & mse_2 < mse_3){
    
    fitX_2 <- ets(y_training)
    fc_ <- forecast::forecast(fitX_2, h=8)$mean  
    chosenM <- "ets" 
    accO <- forecast::accuracy(fc_,y_test)
    
   }else{
     
     result <- mapa(y_training, fh = h, conf.lvl = c(0.8, 0.95))
     fc_ <- result$outfor
     chosenM <- "mapa" 
     accO <- forecast::accuracy(fc_,y_test)
     
   }
     
   
   arr_all[count,4] <- chosenM
   
   arr_all[count,5] <- accO[5]
   
   
  #-----------------------------------------------------
    
   arr_all[count,6] <- M3[[nameId]]$type
   
   arr_all[count,7] <- M3[[nameId]]$sn
   
 
   
  #Count up
  count = count + 1
}

arr_all %>% as_tibble()

```



```{r dynam_hybrid1}


library(forecastHybrid)


arr_all_hyb <- array(NA,c(70,1))

count = 1

for (nameId in arr_ids) {
  
  #MAIN
  h = 8
  
  y_training <- M3[[nameId]]$x  
  y_test <- M3[[nameId]]$xx
  
   #BODY

   fit <- forecastHybrid::hybridModel(y_training, models= "aez")
   fcc <- forecast::forecast(fit,h=8)
   
   acc_m <- forecast::accuracy(fcc$mean, y_test)
   
   arr_all_hyb[count] <- acc_m[5]

count <- count + 1 
}


```

```{r dynamic2}


arr_all_hyb <- array(NA,c(70,4))

colnames(arr_all_hyb) <- c("hybrid_Avg_err", "MAPA_Avg_err","chosen","type")

count = 1

for (nameId in arr_ids) {
  
  #MAIN
  h = 8
  fin_fit <- NA
  
  y_training <- M3[[nameId]]$x  
  y_test <- M3[[nameId]]$xx
  
   
   #BODY
  
   arr_all_hyb[count,4] <- M3[[nameId]]$type
  
   
   #hybrid
  
   farHY <- function(x, h){forecast::forecast(forecastHybrid::hybridModel(y_training, models= "aez"), h = h)}
   
   e_ets_x <- forecast::tsCV(y_training, farHY, initial = (length(y_training)-2*h))
   
   mse_X <- sqrt(mean(e_ets_x^2, na.rm=TRUE))
   
   arr_all_hyb[count,1] <- mse_X

   
   #mapa
   
   fmapa <- function(y, h = 8) {
   result <- mapa(y, fh = h, conf.lvl = c(0.8, 0.95))
   list(mean = result$outfor)
   }
   
   e_MAPA <- forecast::tsCV(y_training, fmapa, initial = (length(y_training)-2*h))
   
   mse_Y <- sqrt(mean(e_MAPA^2, na.rm=TRUE))
   
   arr_all_hyb[count,2] <- mse_Y
   
   
   
   if (mse_Y < mse_X) {
     
     fin_fit <- fmapa(y_training, h)
     
     arr_all_hyb[count,3] <- "mapa"
     
     
   } else {
     
     fin_fit <- farHY(y_training, h)
     
     arr_all_hyb[count,3] <- "hybrid"
     

   }
   
   


   
   
count <- count + 1 

}

arr_all_hyb %>% as_tibble()

```