---
title: "Untitled"
author: "Elias Mayer"
date: "21 8 2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}

library(forecastHybrid)
library(Mcomp)
library(forecast)
library(dplyr)
library(tsibble)
library(ggplot2)
library(ggthemes)
library(stringr)




arr_ids <- array(NA,c(70,1))

count = 1 


for (ex in 1:length(M3)){     #figure our correct indexes     DATA Batch
    

   if ((M3[[ex]]$period == "QUARTERLY") & (ex >= 701) & (ex <= 1400) & (ex %% 10 == 2)) {
     
    arr_ids[count,1] <- ex
       
    count = count + 1
     
   }
  
}


arr_all_hyb <- array(NA,c(70,2))

colnames(arr_all_hyb) <- c("hybrid_MAPE","type")

count = 1


for (nameId in arr_ids) {
  
  #MAIN
  h = 8
  
  y_training <- M3[[nameId]]$x  
  y_test <- M3[[nameId]]$xx
  
   #BODY
   arr_all_hyb[count,2] <- M3[[nameId]]$type
  
   #hybrid
   
   fit <- forecastHybrid::hybridModel(y_training, models= "aezf")
  
   farHY <- forecast(fit, h = 8)

   x <- farHY
   
   acc_fin <- accuracy(x, y_test)
   
   arr_all_hyb[count,1] <- acc_fin[2,5]

count <- count + 1 

}



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
